<?php

use App\Http\Controllers\AttendanceController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\ClientController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\FinanceController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\JobController;
use App\Http\Controllers\ModuleController;
use App\Http\Controllers\PrintController;
use App\Http\Controllers\PublicTrackingController;
use App\Http\Controllers\QuotationController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\SettingsController;
use App\Http\Controllers\StaffController;
use App\Http\Controllers\TaskController;
use Illuminate\Support\Facades\Route;

Route::redirect('/', '/dashboard');
Route::get('/login', [AuthController::class, 'create'])->name('login');
Route::post('/login', [AuthController::class, 'store'])->name('login.store');
Route::post('/logout', [AuthController::class, 'destroy'])->name('logout');
Route::get('/tracking', [PublicTrackingController::class, 'index'])->name('tracking');
Route::post('/tracking', [PublicTrackingController::class, 'search'])->name('tracking.search');
Route::redirect('/cek-berkas', '/tracking');
Route::get('/print/invoice/{id}', [PrintController::class, 'invoice'])->name('print.invoice');
Route::get('/print/quotation/{id}', [QuotationController::class, 'print'])->name('print.quotation');
Route::get('/print/tanda-terima/{id}', [PrintController::class, 'legacyReceipt'])->name('print.receipt.legacy');
Route::get('/print/tanda-terima/{type}/{id}', [PrintController::class, 'receipt'])->name('print.receipt');

Route::middleware('legacy.auth')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/dashboard/clients/new', [ClientController::class, 'create'])->name('clients.create');
    Route::resource('dashboard/clients', ClientController::class)->only(['index', 'store', 'show', 'edit', 'update', 'destroy'])->names('clients');
    Route::get('/dashboard/jobs', [JobController::class, 'index'])->name('jobs.index');
    Route::get('/dashboard/jobs/inbound', [JobController::class, 'index'])->name('jobs.inbound');
    Route::get('/dashboard/jobs/completed', [JobController::class, 'index'])->name('jobs.completed');
    Route::get('/dashboard/jobs/processing', [JobController::class, 'index'])->name('jobs.processing');
    Route::get('/dashboard/jobs/new', [JobController::class, 'create'])->name('jobs.create');
    Route::redirect('/dashboard/jobs/new/badan-hukum', '/dashboard/jobs/new?type=badan_hukum');
    Route::redirect('/dashboard/jobs/new/non-badan-hukum', '/dashboard/jobs/new?type=non_badan_hukum');
    Route::redirect('/dashboard/jobs/new/ppat', '/dashboard/jobs/new?type=ppat');
    Route::post('/dashboard/jobs', [JobController::class, 'store'])->name('jobs.store');
    Route::post('/dashboard/jobs/{type}/{id}/notify', [JobController::class, 'notify'])->where('type', 'badan-hukum|non-badan-hukum|ppat|badan_hukum|non_badan_hukum')->name('jobs.notify');
    Route::get('/dashboard/jobs/{id}/invoice', [JobController::class, 'legacyInvoice'])->name('jobs.legacy-invoice');
    Route::get('/dashboard/jobs/{id}/edit/{category}', [JobController::class, 'legacyEdit'])->where('category', 'badan-hukum|non-badan-hukum|ppat|umum')->name('jobs.legacy-edit-category');
    Route::get('/dashboard/jobs/{id}/edit', [JobController::class, 'legacyEdit'])->name('jobs.legacy-edit');
    Route::get('/dashboard/jobs/{id}', [JobController::class, 'legacyShow'])->name('jobs.legacy-show');
    Route::get('/dashboard/jobs/{type}/{id}', [JobController::class, 'show'])->name('jobs.show');
    Route::get('/dashboard/jobs/{type}/{id}/edit', [JobController::class, 'edit'])->name('jobs.edit');
    Route::put('/dashboard/jobs/{type}/{id}/progress', [JobController::class, 'updateProgress'])->name('jobs.progress');
    Route::put('/dashboard/jobs/{type}/{id}', [JobController::class, 'update'])->name('jobs.update');
    Route::delete('/dashboard/jobs/{type}/{id}', [JobController::class, 'destroy'])->name('jobs.destroy');
    Route::delete('/dashboard/attachments/{id}', [JobController::class, 'deleteAttachment'])->name('attachments.destroy');
    Route::get('/dashboard/invoice', [InvoiceController::class, 'index'])->name('invoices.index');
    Route::get('/dashboard/invoice/new', [InvoiceController::class, 'create'])->name('invoices.create');
    Route::post('/dashboard/invoice', [InvoiceController::class, 'store'])->name('invoices.store');
    Route::get('/dashboard/invoice/{id}', [InvoiceController::class, 'show'])->name('invoices.show');
    Route::get('/dashboard/invoice/{id}/edit', [InvoiceController::class, 'edit'])->name('invoices.edit');
    Route::put('/dashboard/invoice/{id}', [InvoiceController::class, 'update'])->name('invoices.update');
    Route::post('/dashboard/invoice/{id}/payment', [InvoiceController::class, 'payment'])->name('invoices.payment');
    Route::post('/dashboard/invoice/{id}/notify', [InvoiceController::class, 'notify'])->name('invoices.notify');
    Route::delete('/dashboard/invoice/{id}', [InvoiceController::class, 'destroy'])->name('invoices.destroy');
    Route::get('/dashboard/quotation', [QuotationController::class, 'index'])->name('quotations.index');
    Route::get('/dashboard/quotation/new', [QuotationController::class, 'create'])->name('quotations.create');
    Route::post('/dashboard/quotation', [QuotationController::class, 'store'])->name('quotations.store');
    Route::get('/dashboard/quotation/{id}', [QuotationController::class, 'show'])->name('quotations.show');
    Route::get('/dashboard/quotation/{id}/edit', [QuotationController::class, 'edit'])->name('quotations.edit');
    Route::put('/dashboard/quotation/{id}', [QuotationController::class, 'update'])->name('quotations.update');
    Route::post('/dashboard/quotation/{id}/publish', [QuotationController::class, 'publish'])->name('quotations.publish');
    Route::post('/dashboard/quotation/{id}/cancel', [QuotationController::class, 'cancel'])->name('quotations.cancel');
    Route::delete('/dashboard/quotation/{id}', [QuotationController::class, 'destroy'])->name('quotations.destroy');
    Route::get('/dashboard/finance', [FinanceController::class, 'index'])->name('finance.index');
    Route::post('/dashboard/finance/income', [FinanceController::class, 'storeIncome'])->name('finance.income.store');
    Route::post('/dashboard/finance/expenses', [FinanceController::class, 'storeExpense'])->name('finance.expenses.store');
    Route::delete('/dashboard/finance/{type}/{id}', [FinanceController::class, 'destroy'])->where('type', 'income|expense|INCOME|EXPENSE')->name('finance.destroy');
    Route::get('/dashboard/pegawai/data', [StaffController::class, 'index'])->name('staff.index');
    Route::get('/dashboard/tasks', [TaskController::class, 'index'])->name('tasks.index');
    Route::get('/dashboard/tasks/{id}/payment-preview', [TaskController::class, 'paymentPreview'])->name('tasks.payment-preview');
    Route::patch('/dashboard/tasks/{id}/payment', [TaskController::class, 'togglePaymentStatus'])->name('tasks.payment');
    Route::get('/dashboard/pegawai/new', [StaffController::class, 'create'])->name('staff.create');
    Route::post('/dashboard/pegawai/data', [StaffController::class, 'store'])->name('staff.store');
    Route::get('/dashboard/pegawai/absensi', [AttendanceController::class, 'index'])->name('attendance.index');
    Route::get('/dashboard/pegawai/absensi/absenku', [AttendanceController::class, 'checkIn'])->name('attendance.checkin');
    Route::post('/dashboard/pegawai/absensi', [AttendanceController::class, 'submit'])->name('attendance.submit');
    Route::delete('/dashboard/pegawai/absensi/{id}', [AttendanceController::class, 'destroy'])->name('attendance.destroy');
    Route::put('/dashboard/pegawai/absensi/{id}', [AttendanceController::class, 'update'])->name('attendance.update');
    Route::get('/dashboard/pegawai/laporan', [AttendanceController::class, 'report'])->name('attendance.report');
    Route::get('/dashboard/pegawai/{id}', [StaffController::class, 'show'])->name('staff.show');
    Route::get('/dashboard/pegawai/{id}/edit', [StaffController::class, 'edit'])->name('staff.edit');
    Route::put('/dashboard/pegawai/data/{id}', [StaffController::class, 'update'])->name('staff.update');
    Route::patch('/dashboard/pegawai/data/{id}/status', [StaffController::class, 'toggleStatus'])->name('staff.status');
    Route::post('/dashboard/pegawai/data/{id}/reset-password', [StaffController::class, 'resetPassword'])->name('staff.reset-password');
    Route::delete('/dashboard/pegawai/data/{id}', [StaffController::class, 'destroy'])->name('staff.destroy');
    Route::get('/dashboard/audit', [ModuleController::class, 'audit'])->name('audit.index');
    Route::get('/dashboard/settings', [SettingsController::class, 'index'])->name('settings.index');
    Route::put('/dashboard/settings', [SettingsController::class, 'update'])->name('settings.update');
    Route::post('/dashboard/settings/upload', [SettingsController::class, 'upload'])->name('settings.upload');
    Route::get('/dashboard/reports', [ReportController::class, 'index'])->name('reports.index');
    Route::get('/dashboard/reports/export', [ReportController::class, 'export'])->name('reports.export');
    Route::get('/dashboard/stats', [ModuleController::class, 'stats'])->name('stats.index');
    Route::get('/dashboard/productivity', [ModuleController::class, 'productivity'])->name('productivity.index');
    Route::get('/dashboard/akta', [ModuleController::class, 'deeds'])->name('deeds.index');
    Route::get('/dashboard/saksi', [ModuleController::class, 'witnesses'])->name('witnesses.index');
});
