<?php
namespace App\Http\Controllers;
use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;use Illuminate\Support\Facades\Hash;use Illuminate\Support\Str;use Inertia\Inertia;
class StaffController extends Controller{
 public function index(Request $r){$q=trim((string)$r->query('search'));$staff=DB::table('user as u')->leftJoin('staff as s','s.userId','=','u.id')->select('u.*','s.photoPath','s.ktpPath','s.id as staffId')->when($q,fn($x)=>$x->where(fn($x)=>$x->where('u.fullName','like',"%{$q}%")->orWhere('u.username','like',"%{$q}%")->orWhere('u.email','like',"%{$q}%")))->orderBy('u.fullName')->paginate(20)->withQueryString();return Inertia::render('Staff/Index',['staff'=>$staff,'search'=>$q,'stats'=>['total'=>DB::table('user')->count(),'active'=>DB::table('user')->where('isActive',true)->count(),'inactive'=>DB::table('user')->where('isActive',false)->count()]]);}
 public function create(){return Inertia::render('Staff/Form',['staff'=>null]);}
 public function show(string $id){$staff=DB::table('user as u')->leftJoin('staff as s','s.userId','=','u.id')->select('u.*','s.photoPath','s.ktpPath','s.id as staffId')->where('u.id',$id)->first();abort_unless($staff,404);$attendance=$staff->staffId?DB::table('attendance')->where('staffId',$staff->staffId)->orderByDesc('date')->limit(15)->get():collect();return Inertia::render('Staff/Show',compact('staff','attendance'));}
 public function edit(string $id){$staff=DB::table('user as u')->leftJoin('staff as s','s.userId','=','u.id')->select('u.*','s.photoPath','s.ktpPath')->where('u.id',$id)->first();abort_unless($staff,404);return Inertia::render('Staff/Form',compact('staff'));}
 public function store(Request $r){$d=$this->validated($r);DB::transaction(function()use($d,$r){$id='user-'.Str::lower(Str::random(12));DB::table('user')->insert(['id'=>$id,'username'=>$d['username'],'email'=>$d['email'],'phone'=>$d['phone']??null,'passwordHash'=>Hash::make($d['password']),'fullName'=>$d['fullName'],'role'=>$d['role'],'isActive'=>true,'birthday'=>$d['birthday']??null,'createdAt'=>now(),'updatedAt'=>now()]);$photo=$r->hasFile('photo')?'/'.$r->file('photo')->store('uploads/staff','public_root'):null;$ktp=$r->hasFile('ktp')?'/'.$r->file('ktp')->store('uploads/staff','public_root'):null;DB::table('staff')->insert(['id'=>'staff-'.Str::lower(Str::random(12)),'userId'=>$id,'photoPath'=>$photo,'ktpPath'=>$ktp,'createdAt'=>now(),'updatedAt'=>now()]);});return redirect()->route('staff.index')->with('success','Pegawai ditambahkan.');}
 public function update(Request $r,string $id){$d=$r->validate(['fullName'=>'required|string|max:255','email'=>'required|email|max:255','phone'=>'nullable|string|max:255','role'=>'required|in:ADMINISTRATOR,PIMPINAN,STAFFADMIN,OB','birthday'=>'nullable|date','isActive'=>'required|boolean','password'=>'nullable|string|min:4','photo'=>'nullable|image|max:5120','ktp'=>'nullable|file|max:10240']);$payload=['fullName'=>$d['fullName'],'email'=>$d['email'],'phone'=>$d['phone']??null,'role'=>$d['role'],'birthday'=>$d['birthday']??null,'isActive'=>$d['isActive'],'updatedAt'=>now()];if(!empty($d['password']))$payload['passwordHash']=Hash::make($d['password']);DB::transaction(function()use($r,$id,$payload){DB::table('user')->where('id',$id)->update($payload);$files=[];if($r->hasFile('photo'))$files['photoPath']='/'.$r->file('photo')->store('uploads/staff','public_root');if($r->hasFile('ktp'))$files['ktpPath']='/'.$r->file('ktp')->store('uploads/staff','public_root');if($files)DB::table('staff')->where('userId',$id)->update([...$files,'updatedAt'=>now()]);});return redirect()->route('staff.show',$id)->with('success','Pegawai diperbarui.');}
 public function toggleStatus(Request $r,string $id){abort_if($r->session()->get('auth_user.id')===$id,422,'Status akun yang sedang dipakai tidak dapat dinonaktifkan.');$user=DB::table('user')->where('id',$id)->first();abort_unless($user,404);DB::table('user')->where('id',$id)->update(['isActive'=>!$user->isActive,'updatedAt'=>now()]);return back()->with('success','Status akun pegawai diperbarui.');}
 public function resetPassword(string $id){abort_unless(DB::table('user')->where('id',$id)->exists(),404);DB::table('user')->where('id',$id)->update(['passwordHash'=>Hash::make('1234'),'updatedAt'=>now()]);return back()->with('success','Password berhasil direset menjadi 1234.');}
 public function destroy(Request $r,string $id){abort_if($r->session()->get('auth_user.id')===$id,422,'Akun yang sedang dipakai tidak dapat dihapus.');DB::transaction(fn()=>[DB::table('staff')->where('userId',$id)->delete(),DB::table('user')->where('id',$id)->delete()]);return back()->with('success','Pegawai dihapus.');}
 private function validated(Request $r):array{return $r->validate(['fullName'=>'required|string|max:255','username'=>'required|string|max:255|unique:user,username','email'=>'required|email|max:255|unique:user,email','phone'=>'nullable|string|max:255','password'=>'required|string|min:4','role'=>'required|in:ADMINISTRATOR,PIMPINAN,STAFFADMIN,OB','birthday'=>'nullable|date','photo'=>'nullable|image|max:5120','ktp'=>'nullable|file|max:10240']);}
}
